services:
  vote:
    build: vote
    scale: 2
    ports:
      - 8080:6080

  redis:
    image: quay.io/xm0uray/quay_ad_11_vvn_img_docker_v1
    ports:
      - 6080
    volumes:
      - redis:/data

volumes:
  redis:
